# 제목
## 작은 제목
### 더 작은 제목
1. 번호항목
2. 항목작성

In [1]:
import numpy as np
import pandas as pd
7//3

2

In [3]:
type("A")

str

In [4]:
type(1)

int

In [9]:
type(2.4)

float

In [10]:
x = 2
x + 1

3

In [11]:
(x+2) * 4

16

In [12]:
def sample_function(data):
    return ((data + 2) * 4)

In [15]:
print(sample_function(3))
print(sample_function(x))

20
16


In [16]:
class Sample_Class:
    def __init__(self, data1, data2):
        self.data1 = data1
        self.data2 = data2
        
    def method2(self):
        return (self.data1 + self.data2)


In [17]:
# 클래스는 '데이터의 구조와 계산 로직'을 묶어둔 목록
# 실제로 데이터를 저장하는 것은 인스턴스
sample_instance = Sample_Class(data1 = 2, data2 = 3)

In [18]:
sample_instance.data1

2

In [20]:
sample_instance.method2()

5

In [22]:
data = 3
if(data < 2):
    print("2보다 작은 데이터입니다.")
else:
    print("2 이상인 데이터입니다.")

2 이상인 데이터입니다.


In [23]:
for i in range(0, 3):
    print(i)

0
1
2


In [24]:
for i in range(0, 3):
    print("hello")

hello
hello
hello


In [4]:
# 2.4 numpy와 pandas 기본
sample_array = np.array([1,2,3,4,5])
sample_array_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [31]:
sample_array_2.shape

(2, 5)

In [35]:
# 등차수열(앞뒤 값의 차이가 동일한 수열) 만드는 방법
# stop으로 지정한 값은 배열에 포함되지 않는다
np.arange(start=1, stop=6, step=1)

array([1, 2, 3, 4, 5])

In [36]:
np.arange(start=0.1, stop=0.8, step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [37]:
# 여러 가지 배열을 만드는 방법(같은 값 잔뜩 채운 배열)
np.tile("A", 5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [38]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [39]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones(3)

array([1., 1., 1.])

In [42]:
# 슬라이싱 : 데이터 추출
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [43]:
d1_array[1:3]

array([2, 3])

In [46]:
d2_array = np.array(
        [[1,2,3,4,5],
         [6,7,8,9,10]])
d2_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
d2_array[0,3]

4

In [50]:
d2_array[1,2:4]

array([8, 9])

In [17]:
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array*2,
    'col3' : ["A", "B", "C", "D", "E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [6]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [13]:
# 2.4.11 데이터프레임 병합
df_1 = pd.DataFrame({
    'col1' : np.array([1,2,3]),
    'col2' : np.array(["A", "B", "C"])
})
df_2 = pd.DataFrame({
    'col1' : np.array([4,5,6]),
    'col2' : np.array(["D", "E", "F"])
})

In [14]:
print(pd.concat([df_1, df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [16]:
# 가로방향
print(pd.concat([df_1, df_2], axis=1))

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [18]:
# 2.4.12 데이터프레임에 열에 대해 작업하기
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [19]:
print(sample_df.col2) # 열이름 지정 호출(.)

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32


In [20]:
print(sample_df["col2"])

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32


In [23]:
print(sample_df[["col2","col3"]]) # 복수 열 추출(리스트형식으로)

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [24]:
print(sample_df.drop("col1", axis=1)) # 지정 열 빼고 추출

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [25]:
# 2.4.13 데이터프레임 행에 대해 작업하기
print(sample_df.head(n=3))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C


In [28]:
print(sample_df.query('index == 0'))
print(sample_df.query('col3 == "A"')) # query로 여러 조건 지정

   col1  col2 col3
0     1     2    A
   col1  col2 col3
0     1     2    A


In [29]:
print(sample_df.query('col3 == "A" | col3 == "D"'))

   col1  col2 col3
0     1     2    A
3     4     8    D


In [30]:
print(sample_df.query('col3 == "A" & col1 == 3'))

Empty DataFrame
Columns: [col1, col2, col3]
Index: []


In [31]:
print(sample_df.query('col3 == "A"')[["col2", "col3"]])

   col2 col3
0     2    A


In [32]:
# 2.4.14 시리즈
type(sample_df)

pandas.core.frame.DataFrame

In [33]:
type(sample_df.col1) # 데이터 프레임에서 1열만 추출하면 시리즈라는 열데이터형으로 바뀜
# 시리즈는 numpy배열과 거의 동일한 작업 가능

pandas.core.series.Series

In [34]:
type(np.array(sample_df.col1)) # 시리즈 → 배열로 변환

numpy.ndarray

In [36]:
type(sample_df.col1.values) # 시리즈 → 배열로 변환(.values변수 활용)

numpy.ndarray

In [37]:
# 2.4.15 함수의 도움말
help(sample_df.query)

Help on method query in module pandas.core.frame:

query(expr, inplace=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that contain spaces or operators by
        surrounding them in backticks. This way you can also escape
        names that start with a digit, or those that  are a Python keyword.
        Basically when it is not valid Python identifier. See notes down
        for more details.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it with ``b``, your query should be ```a a` + b``.
    
        .. versionadded:: 0.25.0
            Backtick quoting introduced.
    
        .. versionadded:: 1.0